### ISSUE TITLE
Build in mono is broken

### ISSUE THREAD

**Issue by thinktainer** [Doxense/foundationdb-dotnet-client#35] opened 2014-09-15 08:52 UTC
I have the latest xamarin mono package installed on ubuntu 14.04. When compiling the solution with build.fsx, the error at the bottom is produced.

I have set up a vagrant vmware vm at git@github.com:thinktainer/monobox.git you can use for running the build in mono.
I have added a build.sh on my branch in order to be able to kick off FAKE on linux, you can pull this from here: https://github.com/thinktainer/foundationdb-dotnet-client/tree/mono. Let me know if you need any more information.

	Project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj" (Build target(s)):
		Target RestorePackages:
			Executing: mono --runtime=v4.0.30319 ../.nuget/NuGet.exe install "packages.config" -source ""  -RequireConsent -solutionDir "../ "
			Restoring NuGet packages...
			To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages'.
		Target PrepareForBuild:
			Configuration: Debug Platform: AnyCPU
			Created directory "/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory/"
		Target ResolveProjectReferences:
			Project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Client/FoundationDB.Client.csproj" (default target(s)):
				Target PrepareForBuild:
					Configuration: Debug Platform: x64
				Target GenerateSatelliteAssemblies:
				No input files were specified for target GenerateSatelliteAssemblies, skipping.
				Target GenerateTargetFrameworkMonikerAttribute:
				Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
				Target CoreCompile:
				Skipping target "CoreCompile" because its outputs are up-to-date.
				Target DeployOutputFiles:
					Copying file from '/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Client/obj/x64/Debug/FoundationDB.Client.dll.mdb' to '/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory/FoundationDB.Client.dll.mdb'
					Copying file from '/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Client/obj/x64/Debug/FoundationDB.Client.dll' to '/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory/FoundationDB.Client.dll'
			Done building project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Client/FoundationDB.Client.csproj".
		Target CopyFilesMarkedCopyLocal:
			Copying file from '/home/vagrant/lib/foundationdb-dotnet-client/packages/Microsoft.Bcl.Immutable.1.1.22-beta/lib/portable-net45+win8+wpa81/System.Collections.Immutable.dll' to '/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory/System.Collections.Immutable.dll'
		Target GenerateSatelliteAssemblies:
		No input files were specified for target GenerateSatelliteAssemblies, skipping.
		Target GenerateTargetFrameworkMonikerAttribute:
		Skipping target "GenerateTargetFrameworkMonikerAttribute" because its outputs are up-to-date.
		Target CoreCompile:
			Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /keyfile:FoundationDB.Storage.Memory.snk /optimize- /out:obj/Debug/FoundationDB.Storage.Memory.dll API/LevelWriter.cs API/MemorySnapshotOptions.cs IO/SnapshotFormat.cs IO/SnapshotWriter.cs IO/SnapshotReader.cs IO/Win32MemoryMappedFile.cs IO/Win32SnapshotFile.cs Core/Value.cs API/MemoryClusterHandler.cs Core/Key.cs Core/Memory/ValueHeap.cs Core/Memory/KeyHeap.cs Core/SequenceComparer.cs Core/NativeKeyComparer.cs Core/TransactionWindow.cs Core/Entry.cs Core/Memory/EntryPage.cs Core/Memory/ElasticHeap`1.cs API/MemoryDatabaseHandler.cs API/MemoryDatabase.cs API/MemoryTransactionHandler.cs Collections/ColaOrderedDictionary.cs Collections/ColaRangeDictionary.cs Collections/ColaRangeSet.cs Collections/ColaStore`1.cs Collections/ColaStore.cs Collections/ColaOrderedSet.cs Utils/UnamangedSliceReader.cs Utils/TaskHelpers.cs Utils/UnmanagedHelpers.cs Utils/UnmanagedSliceBuilderPool.cs Utils/USliceComparer.cs Utils/USlice.cs Utils/UnmanagedSliceStream.cs Utils/UnmanagedMemoryHeap.cs Properties/AssemblyInfo.cs Utils/UnmanagedSliceBuilder.cs Properties/VersionInfo.cs /target:library /unsafe+ /define:"DEBUG;TRACE" /nostdlib /reference:/usr/lib/mono/4.5/System.dll /reference:../packages/Microsoft.Bcl.Immutable.1.1.22-beta/lib/portable-net45+win8+wpa81/System.Collections.Immutable.dll /reference:/usr/lib/mono/4.5/Microsoft.CSharp.dll /reference:/usr/lib/mono/4.5/System.Core.dll /reference:/home/vagrant/lib/foundationdb-dotnet-client/build/output/FoundationDB.Storage.Memory//FoundationDB.Client.dll /reference:/usr/lib/mono/4.5/mscorlib.dll /reference:/usr/lib/mono/4.5/Facades/System.Collections.Concurrent.dll /reference:/usr/lib/mono/4.5/Facades/System.Collections.dll /reference:/usr/lib/mono/4.5/Facades/System.ComponentModel.Annotations.dll /reference:/usr/lib/mono/4.5/Facades/System.ComponentModel.EventBasedAsync.dll /reference:/usr/lib/mono/4.5/Facades/System.ComponentModel.dll /reference:/usr/lib/mono/4.5/Facades/System.Diagnostics.Contracts.dll /reference:/usr/lib/mono/4.5/Facades/System.Diagnostics.Debug.dll /reference:/usr/lib/mono/4.5/Facades/System.Diagnostics.Tools.dll /reference:/usr/lib/mono/4.5/Facades/System.Diagnostics.Tracing.dll /reference:/usr/lib/mono/4.5/Facades/System.Dynamic.Runtime.dll /reference:/usr/lib/mono/4.5/Facades/System.Globalization.dll /reference:/usr/lib/mono/4.5/Facades/System.IO.dll /reference:/usr/lib/mono/4.5/Facades/System.Linq.Expressions.dll /reference:/usr/lib/mono/4.5/Facades/System.Linq.Parallel.dll /reference:/usr/lib/mono/4.5/Facades/System.Linq.Queryable.dll /reference:/usr/lib/mono/4.5/Facades/System.Linq.dll /reference:/usr/lib/mono/4.5/Facades/System.Net.NetworkInformation.dll /reference:/usr/lib/mono/4.5/Facades/System.Net.Primitives.dll /reference:/usr/lib/mono/4.5/Facades/System.Net.Requests.dll /reference:/usr/lib/mono/4.5/Facades/System.ObjectModel.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Emit.ILGeneration.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Emit.Lightweight.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Emit.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Extensions.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.Primitives.dll /reference:/usr/lib/mono/4.5/Facades/System.Reflection.dll /reference:/usr/lib/mono/4.5/Facades/System.Resources.ResourceManager.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Extensions.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.InteropServices.WindowsRuntime.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.InteropServices.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Numerics.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Serialization.Json.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Serialization.Primitives.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.Serialization.Xml.dll /reference:/usr/lib/mono/4.5/Facades/System.Runtime.dll /reference:/usr/lib/mono/4.5/Facades/System.Security.Principal.dll /reference:/usr/lib/mono/4.5/Facades/System.ServiceModel.Http.dll /reference:/usr/lib/mono/4.5/Facades/System.ServiceModel.Primitives.dll /reference:/usr/lib/mono/4.5/Facades/System.ServiceModel.Security.dll /reference:/usr/lib/mono/4.5/Facades/System.Text.Encoding.Extensions.dll /reference:/usr/lib/mono/4.5/Facades/System.Text.Encoding.dll /reference:/usr/lib/mono/4.5/Facades/System.Text.RegularExpressions.dll /reference:/usr/lib/mono/4.5/Facades/System.Threading.Tasks.Parallel.dll /reference:/usr/lib/mono/4.5/Facades/System.Threading.Tasks.dll /reference:/usr/lib/mono/4.5/Facades/System.Threading.Timer.dll /reference:/usr/lib/mono/4.5/Facades/System.Threading.dll /reference:/usr/lib/mono/4.5/Facades/System.Xml.ReaderWriter.dll /reference:/usr/lib/mono/4.5/Facades/System.Xml.XDocument.dll /reference:/usr/lib/mono/4.5/Facades/System.Xml.XmlSerializer.dll /warn:4
			Unhandled Exception:
			Mono.CSharp.InternalErrorException: IO/SnapshotWriter.cs(136,3): FoundationDB.Storage.Memory.IO.SnapshotWriter.<WriteLevelAsync>c__async0.MoveNext() ---> Mono.CSharp.InternalErrorException: (1,1): ---> System.NotImplementedException: The requested feature is not implemented.
			at Mono.CSharp.Indirection.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.MemberExpr.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeCast.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Binary.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Binary.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Arguments.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.CallEmitter.EmitPredefined (Mono.CSharp.EmitContext ec, Mono.CSharp.MethodSpec method, Mono.CSharp.Arguments Arguments, Nullable`1 loc) [0x00000] in <filename unknown>:0
			at Mono.CSharp.CallEmitter.Emit (Mono.CSharp.EmitContext ec, Mono.CSharp.MethodSpec method, Mono.CSharp.Arguments Arguments, Location loc) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodGroupExpr.EmitCall (Mono.CSharp.EmitContext ec, Mono.CSharp.Arguments arguments) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Invocation.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Invocation.EmitStatement (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StatementExpression.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Unsafe.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.For.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ParametersBlock.EmitEmbedded (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer.EmitMoveNext (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer+MoveNextBodyStatement.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer+MoveNextBodyStatement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ParametersBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ToplevelBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			--- End of inner exception stack trace ---
			at Mono.CSharp.ToplevelBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodData.Emit (Mono.CSharp.TypeDefinition parent) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodOrOperator.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Method.Emit () [0x00000] in <filename unknown>:0
			--- End of inner exception stack trace ---
			at Mono.CSharp.Method.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ClassOrStruct.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ClassOrStruct.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Class.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.NamespaceContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.NamespaceContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ModuleContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.AssemblyDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.AssemblyDefinitionStatic.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0
			[ERROR] FATAL UNHANDLED EXCEPTION: Mono.CSharp.InternalErrorException: IO/SnapshotWriter.cs(136,3): FoundationDB.Storage.Memory.IO.SnapshotWriter.<WriteLevelAsync>c__async0.MoveNext() ---> Mono.CSharp.InternalErrorException: (1,1): ---> System.NotImplementedException: The requested feature is not implemented.
			at Mono.CSharp.Indirection.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.MemberExpr.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeCast.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Binary.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Binary.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Arguments.ContainsEmitWithAwait () [0x00000] in <filename unknown>:0
			at Mono.CSharp.CallEmitter.EmitPredefined (Mono.CSharp.EmitContext ec, Mono.CSharp.MethodSpec method, Mono.CSharp.Arguments Arguments, Nullable`1 loc) [0x00000] in <filename unknown>:0
			at Mono.CSharp.CallEmitter.Emit (Mono.CSharp.EmitContext ec, Mono.CSharp.MethodSpec method, Mono.CSharp.Arguments Arguments, Location loc) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodGroupExpr.EmitCall (Mono.CSharp.EmitContext ec, Mono.CSharp.Arguments arguments) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Invocation.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Invocation.EmitStatement (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StatementExpression.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Unsafe.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.For.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Statement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ParametersBlock.EmitEmbedded (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer.EmitMoveNext (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer+MoveNextBodyStatement.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.StateMachineInitializer+MoveNextBodyStatement.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.Block.DoEmit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ExplicitBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ParametersBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.ToplevelBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			--- End of inner exception stack trace ---
			at Mono.CSharp.ToplevelBlock.Emit (Mono.CSharp.EmitContext ec) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodData.Emit (Mono.CSharp.TypeDefinition parent) [0x00000] in <filename unknown>:0
			at Mono.CSharp.MethodOrOperator.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Method.Emit () [0x00000] in <filename unknown>:0
			--- End of inner exception stack trace ---
			at Mono.CSharp.Method.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ClassOrStruct.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ClassOrStruct.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Class.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeDefinition.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.NamespaceContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.NamespaceContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.TypeContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.ModuleContainer.EmitContainer () [0x00000] in <filename unknown>:0
			at Mono.CSharp.AssemblyDefinition.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.AssemblyDefinitionStatic.Emit () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0
			at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0
	/usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets: error : Compiler crashed with code: 1.
		Task "Csc" execution -- FAILED
		Done building target "CoreCompile" in project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj".-- FAILED
	Done building project "/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj".-- FAILED

	Build FAILED.
	Errors:

	/home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj (Build) ->
	/usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

		/usr/lib/mono/xbuild/12.0/bin/Microsoft.CSharp.targets: error : Compiler crashed with code: 1.

		0 Warning(s)
		1 Error(s)

	Time Elapsed 00:00:01.9173210
	Running build failed.
	Error:
	Building /home/vagrant/lib/foundationdb-dotnet-client/FoundationDB.Storage.Memory/FoundationDB.Storage.Memory.csproj failed with exitcode 1.

**Comment by jvandertil** [comment] 2015-03-06 17:01
Yes, this still occurs. Reopening.

**Comment by KrzysFR** [comment] 2015-03-06 17:04
Can you try what I'm describing above? (post from Oct 7 2014)

**Comment by gusmanb** [comment] 2015-03-06 19:05
Hi there.

I did a bit of digging, the problem is not the await, is the pointer
indirections inside an async function, so it's easy to solve:

Add using System.Runtime.InteropServices;

And change the unchecked block at WriteLevelAsync to this:

#if MONO
                    var valuePointer =new IntPtr((void*)
MemoryDatabaseHandler.ResolveValueAtVersion(segment[i], m_sequence));

                    if (valuePointer == IntPtr.Zero)
                        continue;

                    Value value = new Value();

                    Marshal.PtrToStructure(valuePointer, value);

                    var keyPointer = new IntPtr((void*)segment[i]);

                    Key key = new Key();

                    Marshal.PtrToStructure(keyPointer, key);

                    Contract.Assert(key.Size <=
MemoryDatabaseHandler.MAX_KEY_SIZE);

                    // Key Size
                    uint size = key.Size;
                    m_writer.WriteVarint32(size);
                    m_writer.WriteBytesUnsafe(&(key.Data), (int)size);

                    // Value

                    m_writer.WriteVarint64(value.Sequence); // sequence
                    size = value.Size;
                    if (size == 0)
                    { // empty key
                        m_writer.WriteByte(0);
                    }
                    else
                    {
                        m_writer.WriteVarint32(size); // value size
                        m_writer.WriteBytesUnsafe(&(value.Data),
(int)size); // value data
                    }
#else

                    Value* value =
MemoryDatabaseHandler.ResolveValueAtVersion(segment[i], m_sequence);
                    if (value == null)
                    {
                        continue;
                    }
                    Key* key = (Key*)segment[i]; //.ToPointer();

                    Contract.Assert(key != null && key->Size <=
MemoryDatabaseHandler.MAX_KEY_SIZE);

                    // Key Size
                    uint size = key->Size;
                    m_writer.WriteVarint32(size);
                    m_writer.WriteBytesUnsafe(&(key->Data), (int)size);

                    // Value

                    m_writer.WriteVarint64(value->Sequence); // sequence
                    size = value->Size;
                    if (size == 0)
                    { // empty key
                        m_writer.WriteByte(0);
                    }
                    else
                    {
                        m_writer.WriteVarint32(size); // value size
                        m_writer.WriteBytesUnsafe(&(value->Data),
(int)size); // value data
                    }

#endif

Changing that function everything compiles Ok.

John also some notes about the sh script:

-Don't assume .exe files associated to mono, call them with mono
-check for right ssl certificates, use mozroot prior to install nuget or it
fails
-do a nuget restore before starting compilation or it will fail
-FAKE did not found it's libraries, had to do a "cd build" to it find them
-The FAKE project fails to run unit tests System.Exception: NUnit: cannot
run tests (the assembly list is empty)
-NuGet.exe is in camel case and some parts of the project expects it in
lowercase, you need both versions of .exe, .config and .targets files

Would be really great if you fix the script, in this way the client
compilation is 100% functional under mono and may be Christophe can add it
to git.

Those test where done in CentOS 6.6 with mono 3.12

I already have created a pull request with these changes.

Cheers.


2015-03-06 18:04 GMT+01:00 Christophe Chevalier <notifications@github.com>:

**Comment by KrzysFR** [comment] 2015-03-06 19:23
I merged #57 to fix the build issue with SnapshotWriter.cs

**Comment by KrzysFR** [comment] 2015-03-06 19:37
I did not intend for github to autoclose this issue while merging.

Let me know if the last two fixes solve this issue, and then we can close it for good :)

**Comment by gusmanb** [comment] 2015-03-06 19:51
Hi.

It does not compile now, I have cloned a fresh copy and now I'm getting
tons of

"Collections/ColaRangeDictionaryFacts.cs(XX,XX): error CS0103: The name
`Is' does not exist in the current context"



2015-03-06 20:37 GMT+01:00 Christophe Chevalier <notifications@github.com>:

**Comment by gusmanb** [comment] 2015-03-06 19:54
Found the problem, the nuget restore is not being executed, let me see if I
can enable it.

2015-03-06 20:51 GMT+01:00 Agustin Gimenez <geniwab@gmail.com>:

**Comment by gusmanb** [comment] 2015-03-06 20:16
Done, have created the full install script and now it works with a fresh
clone.

2015-03-06 20:54 GMT+01:00 Agustin Gimenez <geniwab@gmail.com>:

**Comment by KrzysFR** [comment] 2015-03-06 20:18
Merged (#58). I also verified that doing the same works on Windows.

**Closed** 2015-03-06 20:22 UTC
Labels: build, mono
